### ISSUE TITLE
/startup-report Not working

### ISSUE THREAD

**Issue by goyal-aman** [maciejwalkowiak/spring-boot-startup-report#10]
I am trying this out and gone through readme twice to confirm if I have missed something. However, I am not getting anything on /startup-reports

<img width="1527" alt="image" src="https://user-images.githubusercontent.com/47478778/226388341-7107150d-ffab-4018-9db4-e86259686c73.png">

I am getting this above error. I am using Gitpod workspace with java 11.0.17. Any suggestions what I might be doing wrong?

**Comment by kapishmalik** [comment]
I believe you need to remove optional element from dependency.

**Comment by maciejwalkowiak** [comment]
Or perhaps it had test scope in example. I just hit the same problem. It is fixed now.
