### ISSUE TITLE
Webflux support

### ISSUE THREAD

**Issue by eduanb** [maciejwalkowiak/spring-boot-startup-report#12]
With webflux applications, the `/startup-report` endpoint just returns 404.

It seems like it is intentional since [this conditional](https://github.com/maciejwalkowiak/spring-boot-startup-report/blob/e3bc087f091d9234765785a3a08535f1c1c843b0/startup-report/src/main/java/com/maciejwalkowiak/spring/boot/startup/StartupEventsAutoConfiguration.java#L33)  in the configuration is not creating the controller in web flux applications.

**Comment by maciejwalkowiak** [comment]
@eduanb would you like to add WebFlux compatibility? PRs are very welcome

**Comment by eduanb** [comment]
@maciejwalkowiak It was less work than expected. I've created a PR here https://github.com/maciejwalkowiak/spring-boot-startup-report/pull/13
