### ISSUE TITLE
Startup Report with Jhipster

### ISSUE THREAD

**Issue by skin27** [maciejwalkowiak/spring-boot-startup-report#18]
The startup report seems like a very nice tool. I would like to use it with my JHipster based project:

https://github.com/assimbly/gateway

This uses Spring Boot (2.7.12) at the backend and Angular at the frontend. I tried to give the startup-report full rights (like I do with for example the OpenAPI page), but didn't show up. If you have time, you may generate a Spring Boot app with Jhipster and see if it can support it:

https://www.jhipster.tech

It takes around 30 minutes to generate a new app. (you may need to justify the Spring Boot dependency after generation, because probably not the latest version).

**Comment by maciejwalkowiak** [comment]
It's been a while since i've worked with JHipster and unfortunately don't have time for it.

**Comment by skin27** [comment]
No, problem. I'll close this ticket then. You can always reopen when the time allows.
