### ISSUE TITLE
Make project compatible with Java 8

### ISSUE THREAD

**Issue by goyal-aman** [maciejwalkowiak/spring-boot-startup-report#7]
Maciej
When try out this tool to check a work project it fails with `java.lang.UnsupportedClassVersionError` err. Project I am trying this on using JDK 1.8.

Any possibilities to add support for JDK 1.8? I am open to working on this.

**Comment by goyal-aman** [comment]
Will try to get this done over coming weekend!

**Comment by goyal-aman** [comment]
@maciejwalkowiak I should change java.version to 8?

**Comment by maciejwalkowiak** [comment]
@goyal-aman yes definitely change the Java version in pom.xml and also in the github workflow. I haven't tested your PR yet but these changes are 100% necessary.
