### ISSUE TITLE
Application fails after injecting the dependency

### ISSUE THREAD

**Issue by h4h-deniz** [maciejwalkowiak/spring-boot-startup-report#8]
Is there are pre-requisites for the tool? I have a java 11 springboot project and it fails after injecting the dependency

`***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    com.maciejwalkowiak.spring.boot.startup.StartupEventsInitializer.initialize(StartupEventsInitializer.java:17)

The following method did not exist:

    'org.springframework.core.metrics.ApplicationStartup org.springframework.context.ConfigurableApplicationContext.getApplicationStartup()'

The method's class, org.springframework.context.ConfigurableApplicationContext, is available from the following locations:

    jar:file:/home/deniz/.m2/repository/org/springframework/spring-context/5.2.9.RELEASE/spring-context-5.2.9.RELEASE.jar!/org/springframework/context/ConfigurableApplicationContext.class`

**Comment by maciejwalkowiak** [comment]
It must be Spring Framework 5.3+. I'll update the readme

**Comment by frozen00000** [comment]
Looks like it also requires [BufferingApplicationStartup ](https://github.com/spring-projects/spring-boot/blob/83668f96af321a59ee4f56553e8487cfdcc6d68e/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/context/metrics/buffering/BufferingApplicationStartup.java)class that was added in Spring Boot 2.4. I think it would be nice to add to the documentation (readme) as well.
